### ISSUE TITLE
Homebrew forumula for emacs' VM (View Mail)

### ISSUE THREAD

**Issue by DiagonalArg** [edavis/homebrew-emacs#1]
@edavis - I only just found you.  I have been asking a question on emacs' VM [at the main git repo](https://github.com/Homebrew/homebrew/issues/40051#issuecomment-105081274).  Would you be willing to comment?  If it works, can I add it?  (Not yet sure how I'd do that, but I'd figure it out! :)

/DA

**Comment by edavis** [comment]
This repository is no longer maintained. Please check out https://github.com/Homebrew/homebrew-emacs. Thanks!
