### ISSUE TITLE
homebrew-emacs tap is no longer under the Homebrew organization

### ISSUE THREAD

**Issue by dunn** [edavis/homebrew-emacs#3]
Due to changes in the criteria for official Homebrew taps, we moved https://github.com/dunn/homebrew-emacs back under my account.  There's a redirect, so you don't necessarily have to update the readme, but thought you should know.

**Comment by edavis** [comment]
Appreciate the heads up. Out of curiosity, what were the criteria changes?

Absolutely great work on the tap, by the way. I actually went looking for homebrew/homebrew-emacs yesterday (for the first time in months) to install something and noticed both the redirect and just how well maintained everything was. It's great seeing the project thriving like this.

**Comment by dunn** [comment]
> Out of curiosity, what were the criteria changes?

Basically if a tap could be merged into the main repository it was.  Large, specialized taps like Science are remaining separate, but Emacs is still pretty niche and most of the formulae don't meet the notability requirements to be in core.

**Comment by edavis** [comment]
👍
